### ISSUE TITLE
I just wanna rock

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#46]
I cannot believe how much I want this idea to work, this idea of Rails 7, Shopify API and NOT having to use React and all the bullshit that goes with that. 

Is anyone else into that here? A brief totally non-scientific survey of all problems Shopify App development show 99% of all problems relate to using NPM and React. We are free of that burden here. But only if we collectively?? boost this to modern Shopify (old being a year ago)...

**Comment by kirillplatonov** [comment]
I totally agree with you on it. I will wrap up my work on upgrade PR (#42) in 1-2 weeks. I also must admit, that keeping up with Shopify updates is difficult, too many changes for embedded apps in one year.

**Comment by resistorsoftware** [comment]
They have blown many many people out of the water. There are so many things changed now. What worked a few months ago, and had worked for years, is now deprecated and OUT. I await your talented twist on the Rails and App and API. Thanks for the update.

**Comment by uurcank** [comment]
@kirillplatonov I am confused about few things about this setup.

Please correct me if I am wrong

1. From my understanding CSRF tokens do not work in the embed view. Hence submitting forms is not possible (or frequently fails) 

2. This gem replaces CSRF with Shopify's session token, which we can trust? 

3. From my testing this code does not intercept or replace CSRF token. Hence rails forms pretty much do not work. Only API calls made to Shopify works and Rails side of things still fail. Do you have any example that shows otherwise?

4. If I ever use a "redirect_to" in any of the controllers that triggers another login flow in shopify_app gem, which means unnecessary flashing in the screen. So controller calculations not usable?

5. Do we need to essentially create single page application with Hotwire for this flow?

6. Is there a way to escape authenticated controller? For example after authenticating with Shopify via app bridge redirect to a page to initiate a cookie session? And then do things the Rails way under embedded view?

**Comment by uurcank** [comment]
@resistorsoftware I agree. React stuff just makes it harder for full-stack devs. Everything could be much simpler. Even the gem is over complicated.

**Comment by resistorsoftware** [comment]
@uucank, I am not having the problems you are. When rendering a CSRF in a layout, there is no difference in Rails AFAIK. I have plenty of forms in my App and no complaints about that anyway. I don't redirect in my controllers much, so I have no idea why that is a problem, but maybe it is. I suspect that pattern is just not as common in a Shopify App. I have not used this App in a SPA way for many Shopify Apps and so I think you can just choose how you like to represent your App.

**Comment by uurcank** [comment]
@resistorsoftware are you using app bridge v3 or v2? I am testing the v3 , which is the branch @kirillplatonov works on

**Comment by resistorsoftware** [comment]
To be super honest, I only used 2 and not 3. I have no idea what wingus wongus shit Shopify claims in their versions. They bump major versions of Polaris when someone on the team has a gas attack and farts for a minute.

**Comment by uurcank** [comment]
@resistorsoftware do you have any problems running your app in Safari with v2 ? Do you get any cookie warnings with it?

**Comment by uurcank** [comment]
@kirillplatonov The last commits does not work. The gem raises ShopifyDomainNotFound error.

Probably a bug in the gem

Could you also please clarify what the app URL should be in Shopify dashboard usinf this example? 

Is it root or "/login"? or the splash page?

**Comment by kirillplatonov** [comment]
> @kirillplatonov The last commits does not work. The gem raises ShopifyDomainNotFound error.
> 
> Probably a bug in the gem

Could you please try it with a clean copy for the latest sample repo? I need some steps and details to reproduce the error.

> Could you also please clarify what the app URL should be in Shopify dashboard usinf this example?
> 
> Is it root or "/login"? or the splash page?

It should be root (splash screen):
<img width="995" alt="CleanShot 2022-11-12 at 17 29 55@2x" src="https://user-images.githubusercontent.com/839922/201478864-e6b26b2b-124d-4ade-a6e0-7832df652a48.png">

**Comment by kirillplatonov** [comment]
> @kirillplatonov I am confused about few things about this setup.
> 
> Please correct me if I am wrong
> 
> 1. From my understanding CSRF tokens do not work in the embed view. Hence submitting forms is not possible (or frequently fails)
> 2. This gem replaces CSRF with Shopify's session token, which we can trust?
> 3. From my testing this code does not intercept or replace CSRF token. Hence rails forms pretty much do not work. Only API calls made to Shopify works and Rails side of things still fail. Do you have any example that shows otherwise?

CSRF protection [is turned off](https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/controller_concerns/csrf_protection.rb) when the Shopify session token is used. However other cookie-based features might not work when third-party cookies are blocked in the browser (eg Safari or Chrome incognito mode). I'm working on a solution for that: https://twitter.com/kirplatonov/status/1568898545901764610

> 4. If I ever use a "redirect_to" in any of the controllers that triggers another login flow in shopify_app gem, which means unnecessary flashing in the screen. So controller calculations not usable?

You have to use client-side redirect via [`turbo_redirect_to`](https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/controllers/application_controller.rb#L6) method. It will keep the Shopify token during redirect.

> 5. Do we need to essentially create single page application with Hotwire for this flow?

Yes, to build embedded apps you have to use SPA of some sort. This sample makes a bet on the server-rendered Hotwire approach. However, you can also use the official react way provided by Shopify.

> 6. Is there a way to escape authenticated controller? For example after authenticating with Shopify via app bridge redirect to a page to initiate a cookie session? And then do things the Rails way under embedded view?

You won't be able to use cookies within the embedded view. But I hope my upcoming solution with ActiveRecord-based session storage for AppBridge will solve the issue. Alternatively, you can always build a non-embedded app. It's easier but it has it's own downsides.

**Comment by uurcank** [comment]
@kirillplatonov 

There are two cases needs to be handled. Installation and opening the app from dashboard.

So when a user installs the app from app store

1- It goes to splash page
2- Redirected to login
3- Oauth starts
4- Lands back to home page

At this point if you navigate to any other part in Shopify dashboard and come back to open the app, you go back to splash page. The splash page opens in embed view.

Nothing redirects user to the homepage at that point. There is no app_bridge involvement since we do not have "shopify-init" in the application layout file.

**Comment by kirillplatonov** [comment]
@uurcank this is already handled. Splash page is root of the app. Every session starts from it. When the splash page is opened it loads `embedded_app` layout which has `load_path` attribute. This attribute is used to redirect user after retrieving JWT token from Shopify: https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/views/layouts/embedded_app.html.erb#L31

I can't reproduce the issue you described in sample app:
https://user-images.githubusercontent.com/839922/201480206-539e363d-b325-43d5-ab6f-d6ead62787d9.mp4

**Comment by uurcank** [comment]
@kirillplatonov  Thanks for clarifying. I believe my issue[ was related to this ](https://github.com/Shopify/shopify_app/issues/1536). I bundle update the gem today again and somehow it works now. 

Few more issues I see:

FORMS
In your code there is no example of a database operation. What would the code look like for a rails form? The javascript intercepts with the Header. Turbo cannot submit forms without a CSRF token present. Submitting forms over stimulus controller would be an overkill and just no point of using Rails for such a setup.

BROWSER BACK BUTTON.
let's say you are to open a new link on the same parent window with a link like <a target="_parent">  If you click back button to go back to Shopify dashboard, which contains the link to your app "myshopify.com/admin/app/xxxx", I get "app cannot be loaded due to cookies" warning. It goes into some sort of oauth loop. 

App bridge does not just load the session because session_token is expired already, which is a problem I believe.

**Comment by kirillplatonov** [comment]
@uurcank 

> FORMS In your code there is no example of a database operation. What would the code look like for a rails form? The javascript intercepts with the Header. Turbo cannot submit forms without a CSRF token present. Submitting forms over stimulus controller would be an overkill and just no point of using Rails for such a setup.

The app includes an example of the form: https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/views/home/index.html.erb#L7
The CSRF is generated for every form automatically by Rails so everything works fine with Turbo. You don't need to use Stimulus for forms.

> BROWSER BACK BUTTON. let's say you are to open a new link on the same parent window with a link like If you click back button to go back to Shopify dashboard, which contains the link to your app "myshopify.com/admin/app/xxxx", I get "app cannot be loaded due to cookies" warning. It goes into some sort of oauth loop.
> 
> App bridge does not just load the session because session_token is expired already, which is the problem I believe.

Clicking the back button right after opening a link in a new tab is a pretty rare use case. But feel free to contribute to the repo if you want to fix it.

**Comment by uurcank** [comment]
@kirillplatonov upon more testing I see what you mean about cookies. I have better understanding now. Thanks so much for the information.

As for back button, I think this needs to be fixed at Shopify level. iFrame cannot see the history of parent so not really possible. I cannot think of any other solution.
