### ISSUE TITLE
uninitialized constant ShopifyApp::EnsureHasSession

### ISSUE THREAD

**Issue by Kurbm** [kirillplatonov/shopify-hotwire-sample#62]
Hey @kirillplatonov,

your latest changes in the authenticated_controller from:

include ShopifyAPP::Authenticated to ShopifyApp::EnsureHasSession

leads to the error uninitialized constant ShopifyApp::EnsureHasSession

Best,
Kurbm

**Comment by resistorsoftware** [comment]
@Kurbm That is actually a valid change, as Shopify App v21 at least, perhaps older, has this concern and so you can just update your App to a newer Shopify version, like v21.3 and then this problem goes away for you. If you want to stay with your older App, either monkeypatch in the new Shopify concern to your App or otherwise mimic what it is doing! 

[EnsureHasSession](https://github.com/Shopify/shopify_app/blob/d746c7fec3432f9d980c2883f6022dc56ba7fcb7/app/controllers/concerns/shopify_app/ensure_has_session.rb)

**Comment by Kurbm** [comment]
@resistorsoftware ah that makes sense. Did forget to update. Thanks.
